component_depth: 1

exclude:
  - /Pods/IQKeyboardManagerSwift/IQKeyboardManagerSwift/.*
  - /Me-iOS/Services/CommonService.swift
  - /Me-iOS/Custom/ShadowButton.swift
  - /Me-iOS/Custom/CustomCornerUIView.swift
  - /Me-iOS/Custom/CornerImageView.swift
  - /Me-iOS/ViewControllers/Main/Vouchers/.*
