component_depth: 1

exclude:
  - /Pods/IQKeyboardManagerSwift/IQKeyboardManagerSwift/IQKeyboardManager.swift
  - /Pods/IQKeyboardManagerSwift/IQKeyboardManagerSwift/IQToolbar/IQToolbar.swift
  - /Me-iOS/Services/CommonService.swift
  - /Me-iOS/Custom/ShadowButton.swift
  - /Me-iOS/Custom/CustomCornerUIView.swift
